Update update-readmes.yml

diff --git a/.github/workflows/update-readmes.yml b/.github/workflows/update-readmes.yml
--- a/.github/workflows/update-readmes.yml
+++ b/.github/workflows/update-readmes.yml
@@ -23,8 +23,14 @@ jobs:
           while IFS= read -r repo; do
             echo "Processing repository: $repo"
 
-            # Clone the repository
-            git clone https://github.com/$repo.git
+            # Clone the repository using HTTPS and Personal Access Token (PAT)
+            git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/$repo.git
+            if [ $? -ne 0 ]; then
+              echo "Failed to clone repository: $repo"
+              continue
+            fi
+
+            # Change directory to the cloned repository
             cd $repo || { echo "Failed to cd into repository $repo"; exit 1; }
 
             # Append content to README.md file
